kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-cron-deployment
  namespace: ingress-nginx
  labels:
    app: sc-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-cron
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sc-cron
    spec:
      containers:
        - name: sc-cron
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 512Mi
          command: ["/bin/sh", "-c"]
          args: ["/app/cron -all"]
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: sc-go
          env:
            - name: PUBLIC_SUPABASE_REFERENCE_ID
              value: ripcxiducccfionzyaqr
            - name: PRODUCTION
              value: "true"
            - name: PUBLIC_API_URL
              value: https://api.stablecog.com
            - name: BUCKET_BASE_URL
              value: stablecog-gwhbg5cwgmgghtcp.z01.azurefd.net
      imagePullSecrets:
        - name: akscr
