apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - deployment_server.yaml
  - deployment_cron.yaml
  - deployment_upload.yaml
  - deployment_discobot.yaml
  - svc.yaml
