kind: Service
apiVersion: v1
metadata:
  name: server-service
  namespace: ingress-nginx
spec:
  selector:
    app: sc-server
  type: ClusterIP
  ports:
    - port: 13337
      targetPort: 13337
---
kind: Service
apiVersion: v1
metadata:
  name: upload-service
  namespace: ingress-nginx
spec:
  selector:
    app: sc-uploadapi
  type: ClusterIP
  ports:
    - port: 13338
      targetPort: 13338
