name: Deploy to Kubernetes
description: Deploy to Kubernetes
inputs:
  image:
    description: Image to deploy
    required: true
  kube_config:
    description: base64 encoded kube config
    required: true
  service:
    description: Name of the service
    required: true
  env:
    description: Environment to deploy to (prod/qa)
    required: true
  embed-title:
    description: Title of the embed
    required: true
runs:
  using: composite
  steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.5.4"

    - name: Set image (QA)
      if: ${{ inputs.env == 'qa' }}
      working-directory: ./k8s/qa
      shell: bash
      run: |
        kustomize edit set image replaceme=${{ inputs.image }}
        kustomize build . > ../ci-deployment.yaml

    - name: Set image (PROD)
      if: ${{ inputs.env == 'prod' }}
      working-directory: ./k8s/prod
      shell: bash
      run: |
        kustomize edit set image replaceme=${{ inputs.image }}
        kustomize build . > ../ci-deployment.yaml

    - name: Set image (Language)
      if: ${{ inputs.env == 'lingua' }}
      working-directory: ./k8s/lingua
      shell: bash
      run: |
        kustomize edit set image replaceme=${{ inputs.image }}
        kustomize build . > ../ci-deployment.yaml

    - name: Set image (Auth)
      if: ${{ inputs.env == 'auth' }}
      working-directory: ./k8s/auth
      shell: bash
      run: |
        kustomize edit set image replaceme=${{ inputs.image }}
        kustomize build . > ../ci-deployment.yaml

    - name: Deploy image to k8s cluster
      uses: bbedward/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube_config }}
      with:
        args: apply -f ./k8s/ci-deployment.yaml
